jwt:
  issuer: "Medgelabs"
  secret: ${JWT_SECRET}

spring:
  main.banner-mode: off
  logging.level:
    org.springframework: ERROR
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/app
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# Actuator
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure.include: "info,health,prometheus"
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger
springfox.documentation.swagger.v2.path: /apis

---
spring.profiles: dev

jwt:
  secret: abc123

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password:
  logging.level:
    org.springframework: INFO